### ISSUE TITLE
Not able to pull chisel:22.04 image

### ISSUE THREAD

**Issue by yashashwi** [canonical/chisel-releases#104]
FROM chisel:22.04 as installer

is giving exception 
 **chisel:22.04: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed**

Pretty sure, no VPN or network issue from my side.
I also checked chisel:22.04 does not exist on docker hub as well.

**Comment by cjdcordeiro** [comment]
Hi @yashashwi 

that image doesn't exist in DH. Am I right to assume you are following this blog: https://ubuntu.com/blog/craft-custom-chiselled-ubuntu-distroless?

If so, please note the writer's comment: 
> # "chisel:22.04" is our previous "chisel" image from Step 1
> # we built and tagged it locally using the Docker CLI

IOW, that image was built locally, in step 1, with the [writer's custom Dockerfile](https://github.com/valentincanonical/chisel/blob/examples/Dockerfile).

I hope that helps.
