### ISSUE TITLE
ubuntu-24.04 release doesn't seem to work

### ISSUE THREAD

**Issue by norrisjeremy** [canonical/chisel-releases#153]
I am unable to build a simple chiseled container using `ubuntu-24.04`:

Example Dockerfile:
```
FROM ubuntu:22.04 AS chisel
ADD https://github.com/canonical/chisel/releases/download/v0.9.0/chisel_v0.9.0_linux_amd64.tar.gz chisel.tar.gz
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates && \
    tar -xvf chisel.tar.gz -C /usr/bin/ && \
    mkdir -p /rootfs && \
    chisel cut --release ubuntu-24.04 --root /rootfs \
      base-files_base \
      base-files_release-info \
      base-passwd_data \
      libc6_config \
      libc6_libs \
      libgcc-s1_libs \
      dash_bins

FROM scratch
COPY --from=chisel /rootfs /
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["echo foo"]
```

If I then try to build & execute this container, I get an error:
```
$ docker build . -t foo:1 && docker run -it --rm foo:1
...
exec /bin/sh: no such file or directory
```

Simply changing to `ubuntu-22.04` as follows:
```
FROM ubuntu:22.04 AS chisel
ADD https://github.com/canonical/chisel/releases/download/v0.9.0/chisel_v0.9.0_linux_amd64.tar.gz chisel.tar.gz
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates && \
    tar -xvf chisel.tar.gz -C /usr/bin/ && \
    mkdir -p /rootfs && \
    chisel cut --release ubuntu-22.04 --root /rootfs \
      base-files_base \
      base-files_release-info \
      base-passwd_data \
      libc6_config \
      libc6_libs \
      libgcc-s1_libs \
      dash_bins

FROM scratch
COPY --from=chisel /rootfs /
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["echo foo"]
```

And then building & executing this container works:
```
$ docker build . -t bar:1 && docker run -it --rm bar:1
...
foo
```

Is there some package/slice that was introduced in 24.04 that I am missing that needs to be added in order to build a simple chiseled container?

**Comment by cjdcordeiro** [comment]
Hi.

the `dash` package has changed in 24.04 and the binaries are now located at `/usr/bin`. See https://github.com/canonical/chisel-releases/blob/ubuntu-24.04/slices/dash.yaml#L8-L9

**Comment by norrisjeremy** [comment]
Hi @cjdcordeiro,

Please reopen this, as that's not the issue.
`/bin` is a symlink pointing to `/usr/bin`, so executing `/bin/sh` is perfectly fine.

I've actually tracked down the issue.
The problem is that when `/bin/sh` is exec'd, it attempts to open `/lib64/ld-linux-x86-64.so.2`.
This no longer exists in 24.04, as the actual path is now `/usr/lib64/ld-linux-x86-64.so.2`.
For regular 24.04, this is handled fine because `/lib64` is a symlink pointing to `usr/lib64`.
However, with the chisel'd container I'm creating in the example Dockerfiles, `/lib64` is created as a now empty directory, instead of being a symlink to `usr/lib64` as it should be.

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
> Hi @cjdcordeiro,
> 
> Please reopen this, as that's not the issue. `/bin` is a symlink pointing to `/usr/bin`, so executing `/bin/sh` is perfectly fine.
> 
> I've actually tracked down the issue. The problem is that when `/bin/sh` is exec'd, it attempts to open `/lib64/ld-linux-x86-64.so.2`. This no longer exists in 24.04, as the actual path is now `/usr/lib64/ld-linux-x86-64.so.2`. For regular 24.04, this is handled fine because `/lib64` is a symlink pointing to `usr/lib64`. However, with the chisel'd container I'm creating in the example Dockerfiles, `/lib64` is created as a now empty directory, instead of being a symlink to `usr/lib64` as it should be.
> 
> Thanks, Jeremy

Sorry, I misspoke slightly: the symlink for `/lib64` pointing to `usr/lib64` is missing entirely.
If I manually add it, then everything works:

```
FROM ubuntu:22.04 AS chisel
ADD https://github.com/canonical/chisel/releases/download/v0.9.0/chisel_v0.9.0_linux_amd64.tar.gz chisel.tar.gz
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates && \
    tar -xvf chisel.tar.gz -C /usr/bin/ && \
    mkdir -p /rootfs && \
    chisel cut --release ubuntu-24.04 --root /rootfs \
      base-files_base \
      base-files_release-info \
      base-passwd_data \
      libc6_config \
      libc6_libs \
      libgcc-s1_libs \
      dash_bins
RUN ln -s usr/lib64 /rootfs/lib64

FROM scratch
COPY --from=chisel /rootfs /
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["echo foo"]
```

```
$ docker build . -t foo:2 && docker run -it --rm foo:2
...
foo
```

**Comment by norrisjeremy** [comment]
Something like this would fix it I think:
```
diff --git a/slices/libc6.yaml b/slices/libc6.yaml
index 5f67118..7310473 100644
--- a/slices/libc6.yaml
+++ b/slices/libc6.yaml
@@ -28,3 +28,4 @@ slices:
       /usr/lib/*-linux-*/libthread_db.so.*:
       /usr/lib/*-linux-*/libutil.so.*:
       /usr/lib*/ld*.so.*:
+      /lib64:
```
