### ISSUE TITLE
Add additional packages to ubuntu-22.04 & ubuntu-24.04?

### ISSUE THREAD

**Issue by norrisjeremy** [canonical/chisel-releases#155]
1) Would it be possible to add libc-bin to ubuntu-24.04 as was done for ubuntu-22.04 in d3c1f481ea560df01a89fa589a89d01e770ff5b8?
I suspect it's simply a matter of committing a copy of `libc-bin.yaml` from the ubuntu-22.04 branch onto the ubuntu-24.04 branch?

2) Would it be possible to add busybox to ubuntu-24.04?
I suspect it's simply a matter of committing a copy of `busybox.yaml` from the ubuntu22.04 branch onto the ubuntu-24.04, with adjustments for the `/bin` to `/usr/bin` transition?

3) Would it be possible to add netbase to ubuntu-22.04 as was done for ubuntu 24.04 in 45ae94a2661fe919f5598b1a26bbfa10b684c274?
I suspect it's simply a matter of committing a copy of `netbase.yaml` from the ubuntu-24.04 branch onto the ubuntu-22.04 branch?

**Comment by norrisjeremy** [comment]
FYI, I’m happy to submit some PR’s to implement this, but it’s not clear to me if I need to execute a CLA first?
If so, that might take a bit of time as I’d need to submit it through my employer.

**Comment by rebornplusplus** [comment]
Hi Jeremy.

It would be nice if you could add the changes you listed. While doing so, we encourage you to sign the [CLA](https://ubuntu.com/legal/contributors).
@cjdcordeiro might be able to tell you more about the exact requirements on this -- whether it is a must or not.

**Comment by norrisjeremy** [comment]
Hi @rebornplusplus,

Yes, please let me know if signing a CLA is mandatory or not.
It would impact how quickly I could submit PRs.

Thanks!
Jeremy

**Comment by cjdcordeiro** [comment]
Hey !! Your contribution would be highly appreciated :)

And yeah, about the CLA, our CI isn't enforcing it **yet**, but our [CONTRIBUTING policies](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#canonical-contributor-licence-agreement) do. You just need to do it once though, and you'll be good for all future PRs!

**Comment by norrisjeremy** [comment]
Ok, I'll speak with my employer about submitting a CLA, thanks.

**Comment by norrisjeremy** [comment]
Hi @cjdcordeiro,

I've submitted a CLA this morning and have opened several PRs.
Please let me know if there is anything else you need me to do!

Thanks,
Jeremy

**Comment by cjdcordeiro** [comment]
Hi @norrisjeremy ! That's awesome. Thanks

I'll enable the CI for your PRs, including the CLA validation.

We'll get to your PRs as soon as possible.
