### ISSUE TITLE
Missing copyright files for some slices

### ISSUE THREAD

**Issue by norrisjeremy** [canonical/chisel-releases#156]
I've noticed that some slices are missing their copyright files under /usr/share/doc.
For example, this seems to affect the libgcc-s1 & libstdc++6 slices.
I believe this is due to the fact that their directories under /usr/share/doc are actually symlinks to the gcc-base-X package they come from.
And since the gcc-base-X directory under /usr/share/doc is from a different package, it never ends up getting pulled and extracted.
I'm not sure how this should be best handled (if at all)?

**Comment by linostar** [comment]
> I've noticed that some slices are missing their copyright files under /usr/share/doc.
> For example, this seems to affect the libgcc-s1 & libstdc++6 slices.
> I believe this is due to the fact that their directories under /usr/share/doc are actually symlinks to the gcc-base-X package they come from.
> And since the gcc-base-X directory under /usr/share/doc is from a different package, it never ends up getting pulled and extracted.
> I'm not sure how this should be best handled (if at all)?

We don't include docs and man pages in slices on purpose, since they are not needed for the libs or binaries to work. And if I'm not mistaken, that applies to copyright and license files as well.

**Comment by norrisjeremy** [comment]
Yes you do.
See https://github.com/canonical/chisel/blob/11a324ceca40c373ae5298ff6b93986340a945d7/internal/slicer/slicer.go#L90.

**Comment by norrisjeremy** [comment]
```
$ chisel cut --release ubuntu-22.04 --root foo libc6_libs
2024/02/28 14:44:21 Consulting release repository...
2024/02/28 14:44:22 Fetching current ubuntu-22.04 release...
2024/02/28 14:44:22 Processing ubuntu-22.04 release...
2024/02/28 14:44:22 Selecting slices...
2024/02/28 14:44:22 Fetching ubuntu 22.04 jammy suite details...
2024/02/28 14:44:22 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/02/28 14:44:22 Fetching index for ubuntu 22.04 jammy main component...
2024/02/28 14:44:22 Fetching index for ubuntu 22.04 jammy universe component...
2024/02/28 14:44:23 Fetching ubuntu 22.04 jammy-security suite details...
2024/02/28 14:44:23 Release date: Wed, 28 Feb 2024 20:15:03 UTC
2024/02/28 14:44:23 Fetching index for ubuntu 22.04 jammy-security main component...
2024/02/28 14:44:23 Fetching index for ubuntu 22.04 jammy-security universe component...
2024/02/28 14:44:23 Fetching ubuntu 22.04 jammy-updates suite details...
2024/02/28 14:44:23 Release date: Wed, 28 Feb 2024 20:15:54 UTC
2024/02/28 14:44:23 Fetching index for ubuntu 22.04 jammy-updates main component...
2024/02/28 14:44:23 Fetching index for ubuntu 22.04 jammy-updates universe component...
2024/02/28 14:44:23 Fetching pool/main/g/glibc/libc6_2.35-0ubuntu3.6_amd64.deb...
2024/02/28 14:44:23 Extracting files from package "libc6"...
$ ls foo/usr/share/doc/libc6/copyright 
foo/usr/share/doc/libc6/copyright
```

**Comment by linostar** [comment]
> Yes you do. See https://github.com/canonical/chisel/blob/11a324ceca40c373ae5298ff6b93986340a945d7/internal/slicer/slicer.go#L90.

Sorry for the confusion, I was referring to the contents of slice definition files. But yes you're correct, copyright is included regardless if it is located correctly in the source package.

**Comment by rebornplusplus** [comment]
Currently in Chisel, we take a look at the files listed in the slices we are about to install and if the copyright path (usually `/usr/share/doc/<pkg>/copyright` is not listed there, we add the path to one of the slices from within Chisel. That is why you do not usually see the copyright paths listed in any of the slice definition files.

But as you pointed out, there are exceptions where a package does not have the copyright file within itself and may rely on another package to provide the copyright. In those cases, one thing we could do is add a `copyright` slice in the slice definition files.

In the particular case of `libgcc-s1`, the following might be a solution to add the copyright file:
```yaml
package: libgcc-s1

slices:
  ...
  copyright:
    essential:
      - gcc-12-base_copyright
    contents:
      /usr/shared/doc/libgcc-s1:
```

```yaml
package: gcc-12-base

slices:
  copyright:
    # we probably do not need to list the copyright file
    # since chisel will add it anyway.
```

It works too:
```
$ chisel cut --release ./ --root out/ libgcc-s1_copyright
2024/02/29 13:41:55 Processing ./ release...
2024/02/29 13:41:56 Selecting slices...
2024/02/29 13:41:56 Fetching ubuntu 22.04 jammy suite details...
2024/02/29 13:41:58 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/02/29 13:41:58 Fetching index for ubuntu 22.04 jammy main component...
2024/02/29 13:41:58 Fetching index for ubuntu 22.04 jammy universe component...
2024/02/29 13:41:59 Fetching ubuntu 22.04 jammy-security suite details...
2024/02/29 13:41:59 Release date: Thu, 29 Feb 2024  7:07:36 UTC
2024/02/29 13:41:59 Fetching index for ubuntu 22.04 jammy-security main component...
2024/02/29 13:41:59 Fetching index for ubuntu 22.04 jammy-security universe component...
2024/02/29 13:41:59 Fetching ubuntu 22.04 jammy-updates suite details...
2024/02/29 13:41:59 Release date: Thu, 29 Feb 2024  7:08:34 UTC
2024/02/29 13:41:59 Fetching index for ubuntu 22.04 jammy-updates main component...
2024/02/29 13:41:59 Fetching index for ubuntu 22.04 jammy-updates universe component...
2024/02/29 13:41:59 Fetching pool/main/g/gcc-12/gcc-12-base_12.3.0-1ubuntu1~22.04_amd64.deb...
2024/02/29 13:41:59 Fetching pool/main/g/gcc-12/libgcc-s1_12.3.0-1ubuntu1~22.04_amd64.deb...
2024/02/29 13:41:59 Extracting files from package "gcc-12-base"...
2024/02/29 13:41:59 Extracting files from package "libgcc-s1"...
```

```
$ tree out/
out/
└── usr
    └── share
        └── doc
            ├── gcc-12-base
            │   └── copyright
            └── libgcc-s1 -> gcc-12-base
```

**Comment by norrisjeremy** [comment]
Yes, it would be great if something like this could be done for packages like `libgcc-s1` & `libstdc++6`.

**Comment by rebornplusplus** [comment]
Nice, thank you!

**Comment by cjdcordeiro** [comment]
These have been added to libgcc-s1 & libstdc++6.
