### ISSUE TITLE
create Chisel release for 23.04

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel-releases#24]
Now that the Lunar archives are live, we should create a new Chisel release for this release.

**Comment by SamirPS** [comment]
Hey,

I have forked the repository and created a new Chisel release see here : [https://github.com/SamirPS/chisel-releases/tree/ubuntu-23.04](url) and all slices work well. The only modification I have done is not related to lunar, kinetic or jammy but to a typo.

I change the mutate script slices/base-passwd.yaml to : 

```
mutate: |
      gr = content.read("/usr/share/base-passwd/group.master")
      content.write("/etc/group", gr)
      pw = content.read("/usr/share/base-passwd/passwd.master")
      content.write("/etc/passwd", pw)
```

But I see that it's already a PR for kinetic and jammy.
