### ISSUE TITLE
Add libgomp1 to slices

### ISSUE THREAD

**Issue by alonyado** [canonical/chisel-releases#246]
libgomp1 package is missing in slices for 24.04 branch.
libgomp1 is OpenMP library which is very common.

**Comment by alonyado** [comment]
Added slice libgomp1.yaml:
```
package: libgomp1

slices:
  libs:
    essential:
      - libc6_libs
    contents:
      /usr/lib/*-linux-*/libgomp.so.1*:
```

Test results, inside ubuntu-24.04 image docker:

```
sudo apt-get update && sudo apt-get -y install golang-go  ca-certificates
go install github.com/canonical/chisel/cmd/chisel@latest
mkdir -p /test
/root/go/bin/chisel cut --release ./ --root /test libgomp1_libs
```

====output====
024/05/13 07:00:34 Processing ./ release...
2024/05/13 07:00:34 Selecting slices...
2024/05/13 07:00:34 Fetching ubuntu 24.04 noble suite details...
2024/05/13 07:00:35 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/05/13 07:00:35 Fetching index for ubuntu 24.04 noble main component...
2024/05/13 07:00:36 Fetching index for ubuntu 24.04 noble universe component...
2024/05/13 07:00:38 Fetching ubuntu 24.04 noble-security suite details...
2024/05/13 07:00:38 Release date: Fri, 10 May 2024 17:51:58 UTC
2024/05/13 07:00:38 Fetching index for ubuntu 24.04 noble-security main component...
2024/05/13 07:00:38 Fetching index for ubuntu 24.04 noble-security universe component...
2024/05/13 07:00:39 Fetching ubuntu 24.04 noble-updates suite details...
2024/05/13 07:00:39 Release date: Mon, 13 May 2024  6:15:30 UTC
2024/05/13 07:00:39 Fetching index for ubuntu 24.04 noble-updates main component...
2024/05/13 07:00:39 Fetching index for ubuntu 24.04 noble-updates universe component...
2024/05/13 07:00:39 Fetching pool/main/g/glibc/libc6_2.39-0ubuntu8.1_amd64.deb...
2024/05/13 07:00:39 Fetching pool/main/g/gcc-14/libgomp1_14-20240412-0ubuntu1_amd64.deb...
2024/05/13 07:00:39 Extracting files from package "libc6"...
2024/05/13 07:00:40 Extracting files from package "libgomp1"...
====
check that library is ok:
`ldd /test/usr/lib/x86_64-linux-gnu/libgomp.so.1
`====output====
linux-vdso.so.1 (0x00007ffec82db000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffb17c47000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffb17eb5000)

**Comment by SamirPS** [comment]
Hey,

I just saw that the slice exist, so i think we can close this issue :)
