### ISSUE TITLE
missing copyright slice for python3.*-venv

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel-releases#272]
https://github.com/canonical/chisel-releases/blob/ff34d1fda124dd906492a4ebe52df9da85e15d76/slices/python3.11-venv.yaml#L2

@gregory-schiano I believe we unintentionally left out the copyright slice, which in this case is a symlink, so it should look something like

```yaml
/usr/share/doc/python3.12-venv: {symlink: /usr/share/doc/python3.12/copyright} 
# or even 
# /usr/share/doc/python3.12-venv: 
# but that could bring additional file that we don't need
```

**Comment by norrisjeremy** [comment]
I think this issue can be closed now?

**Comment by cjdcordeiro** [comment]
Yes, #390 has been merged
