### ISSUE TITLE
CLA signed, but checks not passing as I seem to be not added to contributor list(s)

### ISSUE THREAD

**Issue by timo-reymann** [canonical/chisel-releases#288]
Firstly, I apologize for opening an GitHub issue for this, but I couldn't find any support info on the CLA signing page. In [FAQs](https://ubuntu.com/legal/contributors/faq), this is also not really covered (or I did not find it).

So I signed the Individual Contributor Agreement form over here:
https://ubuntu.com/legal/contributors/agreement

Which resulted in a success message “you can now contribute …”, but I got no mail, I am not in the list it seems and also not part of the group on launchpad.

What exactly is the process here? — Do I just need to wait for a sync, will I get a mail?

**Comment by cjdcordeiro** [comment]
Hi. Did you sign up as `[timo-reymann](https://github.com/timo-reymann)`? If so, indeed I cannot find your submission. Did you check your spam folder?

**Comment by timo-reymann** [comment]
Jep nothing :/

Tried gmail and my personal domain

**Comment by cjdcordeiro** [comment]
Can you please report your problem here: https://launchpad.net/~contributor-agreement-canonical/+contactuser

**Comment by timo-reymann** [comment]
Sent a message to the launchpad list. 

It was not quite clear whom to contact as chisel is not listed on the projects page and there is no general contact 😅 

Will close this for now, as I hope can clarify it via the [“Canonical Contributor Agreement” team](https://launchpad.net/~contributor-agreement-canonical)
