### ISSUE TITLE
ca-certificates broken for ubuntu 22.04

### ISSUE THREAD

**Issue by davidgross-forge** [canonical/chisel-releases#295]
When calling `chisel` with `ca-certificates_data` (or any of the other iterations, `ca-certificates_bins`, etc). I get this error:
```
66.21 error: cannot extract from package "ca-certificates": when using wildcards source and target paths must match: /usr/share/ca-certificates/mozilla/**
```

This is a very basic image and it worked until prior to #267 being merged.

**Comment by rebornplusplus** [comment]
Hi David, will you please tell me which version of Chisel you are using?

**Comment by davidgross-forge** [comment]
v0.9.1

**Comment by rebornplusplus** [comment]
Ah oka, must be that. Please update to v0.10.0, there were some fixes in the new version. It should work like before.

Let me know if it doesn't!

**Comment by davidgross-forge** [comment]
It appears that upgrading to v0.10.0 did fix it.
