### ISSUE TITLE
status of database and effort?

### ISSUE THREAD

**Issue by jf** [canonical/chisel-releases#34]
I recently came across Chisel and was pretty excited about using it. That is, until I came to this database and see that this is nowhere as complete as I'd thought it would be. What is the status of the database, and how much resources is Canonical devoting to actually making this a complete database? The list here (https://github.com/canonical/chisel-releases/tree/ubuntu-22.04/slices) is hardly complete.

**Comment by renaudcerrato** [comment]
I just discovered Chisel and came through the same conclusion. I found the ubuntu/jre docker images, but unable to find the slice for openjdk-17 here!

**Comment by cjdcordeiro** [comment]
Hi folks,

@jf this database is growing. It is however heavily reliant on community efforts. 

Ideally, the slice definitions should come from the package maintainers who want to make their packages available through slices. After all, package maintainers are the ones with the appropriate knowledge and motivation to slice their packages.

Nonetheless, we do have a group of people who are committed to contributing to this database by defining the slices for packages they don't own (as you can see from the contributions in https://github.com/canonical/chisel-releases/pulls). 

We'd love to have the open-source community contributing to the definition of slices, so we strongly encourage you (and people who need new slices) to become contributors.

---

@renaudcerrato I saw you got a reply in https://github.com/canonical/chisel-releases/issues/67, so I hope that helps. Remember that slices are defined **per Ubuntu release**, so while you might not be able to find the slice definitions for openjdk-17 in one release, they might be available on another. FYI, there's a new `chisel` command [incoming](https://github.com/canonical/chisel/pull/101) ("find") that will make the discovery of slices much easier.
