### ISSUE TITLE
Add `tzdata-legacy` slice for 24.04

### ISSUE THREAD

**Issue by lbussell** [canonical/chisel-releases#405]
The `tzdata-legacy` slice is needed to make migrating from 22.04 to 24.04 easier. We have one user requesting this package be added in .NET 24.04 images (https://github.com/dotnet/dotnet-docker/issues/6078). I'd like to evaluate the package to potentially include it in our images, but a slice will be necessary to prototype this.

Documented in the [24.04 Noble release notes](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890):

> Please install tzdata-legacy in case you need the legacy timezones or to restore the previous behavior. This might be needed in case the system provides timezone-aware data over the network (e. g. SQL databases).

**Comment by rebornplusplus** [comment]
Added #412 for the tzdata-legacy slices.

I wondered if we should have a `tzdata_legacy-zoneinfo` slice which contains the `tzdata-legacy_zoneinfo`, but I guess it will just be very odd to look at -- the dependencies going back and forth. If somebody needs the extra timezones, I think they should just install it additionally from the `tzdata-legacy_zoneinfo` slice.

**Comment by rebornplusplus** [comment]
Closed by #412.
