### ISSUE TITLE
Where are the slices for ubuntu/jre images ? 

### ISSUE THREAD

**Issue by renaudcerrato** [canonical/chisel-releases#67]
Hi there (if there's still someone around)!

Where are the slices for openjdk-17 used to build https://hub.docker.com/r/ubuntu/jre?

**Comment by rebornplusplus** [comment]
Hiya!

You can find the slices for Java 17 runtime dependencies at https://github.com/canonical/chisel-releases/pull/39. Additionally, I believe you can find the Dockerfile used to build the ubuntu/jre image on Dockerhub here: https://github.com/ubuntu-rocks/chiselled-jre/tree/channels/17/edge.

Cheers.
