### ISSUE TITLE
Where is the slice for Systemd?

### ISSUE THREAD

**Issue by yashashwi** [canonical/chisel-releases#75]
RIght now all the slices are given considering we are creating a base image "From scratch", this will mean that our containers can only run single binaries which we have provided.

How can we chisel a image such that we can run multiple processes?

1. how can we create docker image with supporting packages like : apt, systemd
2. If we want additional packages like apache2 inside our docker image, how can we assemble it?

**Comment by cjdcordeiro** [comment]
Hi @yashashwi 

you can also install slices on an existing non-chiselled filesystem. Chisel behaves very much like a package manager, but for package slices.

> How can we chisel a image such that we can run multiple processes?

We recommend using [Pebble](https://github.com/canonical/pebble). This is a process manager that is tailored for container use. In fact, many of our application container images run with it (e.g. https://hub.docker.com/r/ubuntu/prometheus). It's a single binary so no need to chisel it. 

> how can we create docker image with supporting packages like : apt, systemd

these are all debs that would need to be sliced first. We don't have the slice definitions for them yet, but we would welcome the community contribution

> If we want additional packages like apache2 inside our docker image, how can we assemble it?

Very much like any other package: create the slice definitions files for apache2, and then use chisel to install the desired slices. Here's a similar example for Nginx: https://discourse.ubuntu.com/t/a-teeny-weeny-itty-bitty-pocket-sized-chiselled-nginx-image/38481.

I hope this answers your questions ;) please re-open if you have further questions.

**Comment by yashashwi** [comment]
Hi cjdcordeiro
Copying chiselled filesystem on an existing non-chiselled filesystem, won't it break the whole purpose. We will have to then remove unnecessary file systems? To keep the image leaner?
> you can also install slices on an existing non-chiselled filesystem. Chisel behaves very much like a package manager, but for package slices.
> 
> > How can we chisel a image such that we can run multiple processes?
> 
> We recommend using [Pebble](https://github.com/canonical/pebble). This is a process manager that is tailored for container use. In fact, many of our application container images run with it (e.g. https://hub.docker.com/r/ubuntu/prometheus). It's a single binary so no need to chisel it.
> 
> > how can we create docker image with supporting packages like : apt, systemd
> 
Is this a work in progress? Is creating all slices for difference packages a work in progress? How do we determine slice definitions?Am Happy to contribute.
> these are all debs that would need to be sliced first. We don't have the slice definitions for them yet, but we would welcome the community contribution
> 
> > If we want additional packages like apache2 inside our docker image, how can we assemble it?
> 
> Very much like any other package: create the slice definitions files for apache2, and then use chisel to install the desired slices. Here's a similar example for Nginx: https://discourse.ubuntu.com/t/a-teeny-weeny-itty-bitty-pocket-sized-chiselled-nginx-image/38481.
> 
> I hope this answers your questions ;) please re-open if you have further questions.

**Comment by cjdcordeiro** [comment]
> Copying chiselled filesystem on an existing non-chiselled filesystem, won't it break the whole purpose. We will have to then remove unnecessary file systems? To keep the image leaner?

Chisel only installs slices from Debian packages, and more often that not, your images will be a combination of debs, snaps, binaries, sources, etc. It really depends on your use case. You should slice as much as you can (and that's debs).

> Is this a work in progress? Is creating all slices for difference packages a work in progress? How do we determine slice definitions?Am Happy to contribute.

Those two packages are not yet being sliced by anyone afaik. We'd be happy to consider your contribution. I'll be committing some guidelines before the end of next week, but in the meantime, you can have a look at the existing slices in this repository, plus their schema in https://github.com/canonical/chisel#slice-definitions, to understand how these are defined.

**Comment by yashashwi** [comment]
HI cjdcordeiro,

In last discussion, you informed, you will be creating guidelines for writing slices.yaml file. Is it done?
I went through this https://github.com/canonical/chisel#slice-definitions, and it is very high level. I wanted to know:
what data, content, essentials . I mean initially I thought they are names for existing slices, but checked some of the existing slices, and the slices mentioned for these tags are not defined.

2. how do you decide, libs and config tags in yaml. 
I am going through the code to understand how these slices are being read.

**Comment by rebornplusplus** [comment]
Hi @yashashwi! Feel free to check out the following links:
* https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md
* https://canonical-rockcraft.readthedocs-hosted.com/en/latest/how-to/create-slice/ 
  (there should be a few other helpful guides related to chisel/slicing as well)
