### ISSUE TITLE
What is the best way to copy custom packages installed?

### ISSUE THREAD

**Issue by ranjanp75** [canonical/chisel-releases#97]
I am planning to create a scratch docker image with all custom packages installed. What is the best way to do this with chisel?

**Comment by cjdcordeiro** [comment]
Hi @ranjanp75 .

There are a few articles that will serve as good examples:
 - https://ubuntu.com/blog/craft-custom-chiselled-ubuntu-distroless
 - https://levelup.gitconnected.com/teeny-weeny-containers-with-chisel-8d9bec38d124

We've also just launched an IRC room dedicated to Chisel questions, so feel free to join us at https://matrix.to/#/#chisel:ubuntu.com
